[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uv run python server.py --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
# Railway will automatically set PORT
# Add your API keys and configuration here
# OPENAI_API_KEY = "your-openai-api-key"
# TAVILY_API_KEY = "your-tavily-api-key"
# SEARCH_API = "tavily"
# ALLOWED_ORIGINS = "https://your-frontend-domain.com"
